Updates snapcraft.yaml file
snapcrafters/axel pull request #7
Opened 2023-02-26 22:32 UTC by plasmus777

This is an update to the snapcraft.yaml file, putting some missing information about the application, such as
title, description, website, issues, donations, and other things.

2023-03-04 21:09 UTC, merlijn-sebrechts requested changes
Thanks for your help! I added some comments about some issues with the metadata, but it should be easy to fix.

I have to admit, I didn't know we had a `donation` URL, so thanks for teaching me about this! :)

2023-03-04 21:09 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> +title: Axel - Lightweight CLI Download Accelerator
Can you remove the part after "Axel"? The title should be just the name, and the title can't be longer than 40 characters.

2023-03-04 21:09 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> +  Axel is a command-line tool to download files, supporting some interesting features:
Please add a space between this line and the next. The description uses markdown. In markdown, paragraphs are separated by a blank line.

2023-03-04 21:09 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> +    - Supports the HTTP, HTTPS, FTP and FTPS protocols.
Please add a space between this line and the next.

2023-03-04 21:09 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> +  The creation of such tool was only possible thanks to the original developer of Axel, Wilmer van der Gaast, and every contributer to the project who worked over the years.
Please add the same "authors" block as is on the other snap. Every `snapcrafters` snap should have this block at the end.

2023-03-04 21:09 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> -
Not a requirement, but I like it when you have a newline before and after the block with `grade`, `confinement` and `base`. So something like this:

```
...
source-code: https://github.com/axel-download-accelerator/axel/
website: https://github.com/axel-download-accelerator/axel/

grade: stable
confinement: strict
base: core18

parts:
...
```

2023-03-04 21:09 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> +donation: |
`donation` can only be a single URL. We can't add multiple. Maybe remove the github one and keep the liberapay, since that gives the biggest share to the developer?

2023-03-05 15:02 UTC, plasmus777 commented
Thanks for all the assistance so far; I've been taking notes that may also help for later creations/changes, including other metadata or projects.

2023-03-05 15:17 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> +  Axel is a command-line tool to download files, supporting some interesting features:
@plasmus777 I apologize, I meant a blank line here, not a space.

2023-03-05 15:17 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> +    - Supports the HTTP, HTTPS, FTP and FTPS protocols.
@plasmus777 I apologize, I meant a blank line here, not a space.

2023-03-05 15:22 UTC, merlijn-sebrechts commented on snap/snapcraft.yaml
> +  Axel is a command-line tool to download files, supporting some interesting features:
The space appears to be why the build is failing at the moment. So it should be something like this:

```
description: |
  Axel is a command-line tool to download files, supporting some interesting features:

  - Usage of multiple connections per file, possibly speeding up the download proccess and also balancing the load between different servers;
  - Very lightweight, which can be useful specially on byte-critical systems;
  - Supports the HTTP, HTTPS, FTP and FTPS protocols.
  
  The creation of such tool was only possible thanks to the original developer of Axel, Wilmer van der Gaast, and every contributer to the project who worked over the years.
     
   **Authors**

  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or officially maintained by the upstream developers.
```

2023-03-05 16:00 UTC, merlijn-sebrechts approved these changes
All good, thanks a lot!

Don't be afraid to make mistakes, this is the best way to learn ;)

2023-03-05 16:00 UTC, merged